//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinActive.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinActive.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///set /a _Debug=0
        ///::==========================================
        ///:: Get Administrator Rights
        ///set _Args=%*
        ///if &quot;%~1&quot; NEQ &quot;&quot; (
        ///  set _Args=%_Args:&quot;=%
        ///)
        ///fltmc 1&gt;nul 2&gt;nul || (
        ///  cd /d &quot;%~dp0&quot;
        ///  cmd /u /c echo Set UAC = CreateObject^(&quot;Shell.Application&quot;^) : UAC.ShellExecute &quot;cmd.exe&quot;, &quot;/k cd &quot;&quot;%~dp0&quot;&quot; &amp;&amp; &quot;&quot;%~dpnx0&quot;&quot; &quot;&quot;%_Args%&quot;&quot;&quot;, &quot;&quot;, &quot;runas&quot;, 1 &gt; &quot;%temp%\GetAdmin.vbs&quot;
        ///  &quot;%temp%\GetAdmin.vbs&quot;
        ///  del /f /q &quot;%temp%\GetAdmin.vbs&quot; 1&gt;nul 2&gt;nul
        ///  exit
        ///)
        ///::==========================================
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KMS_VL_ALL {
            get {
                return ResourceManager.GetString("KMS_VL_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SECOPatcher {
            get {
                object obj = ResourceManager.GetObject("SECOPatcher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vlmcsd {
            get {
                object obj = ResourceManager.GetObject("vlmcsd", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
